### ISSUE TITLE
Disable task

### ISSUE THREAD

**Issue by leghtas** [Ecpy/ecpy#109]
A suggestion: it would be nice to be able to disable a task. For example, we could select a task, go to Execution editor, and check a disable button. This would mean the measure would simply skip this task (which could maybe appear grey in the list of tasks to the left). I think it would be useful for debugging.

**Comment by lcontami** [comment]
@leghtas I don't see how you would use this; what do you mean by debugging ? debugging a measurement or an issue with the interface code ?

**Comment by leghtas** [comment]
For instance, I am transferring 300 waveforms to the AWG, which takes a few minutes. And when I am trying new things (like change the number of averaging for the acquisition card), it would be nice to disable the "transfer pulses" task, since the awg is already loaded with waveforms from the previous measurement. Or sometimes the measure crashes, and to find where the crash is coming from, it would be handy to disable certain tasks and see which one is causing the crash.

**Comment by MatthieuDartiailh** [comment]
You could simply include the transfer task in a Conditional and set the condition to 0 or 1 depending on what you need.

**Comment by MatthieuDartiailh** [comment]
And the manipulation required are not that dramatic (once we include all the fixes for the tree and bugged editors) that it is worth complicating the logic.

**Comment by leghtas** [comment]
Ok agreed.

**Comment by MatthieuDartiailh** [comment]
Then closing
