### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by MatthieuDartiailh** [Ecpy/ecpy#125]
While preparing the first release (after which we will drop Python 2 support cf https://github.com/Ecpy/ecpy/issues/115), I realized that a package named ecpy (actually ECPy but it does not matter) exist already on PyPI (https://pypi.org/search/?q=ecpy) (PyPI is where pip look for package and where all Python packages are released).
As two packages cannot have the same name, we need to at least rename the PyPI package. However to avoid any future issue, I would suggest renaming the project to avoid any clash. Renaming the project should quite painless with the proper tooling (that I have). This would of course affect extension packages. I volunteer to handle the migration both of the main packages and ecpy_qcircuits used by Lyon (I should have been more careful before...).
Ideally I would like to proceed quickly, but first we need a name. I must say I am usually very bad with names. Keeping the meaning of the acronym we could go with `excopy` (Two letters instead of one per word).
I propose that everybody vote (using the little emojis provided by Github below a message). Anybody with a better idea is free to post his idea (and checking first on PyPI that it does not exist). And people can vote for as many ideas as they want. Should we reach an equality I may have to choose a side.

**Comment by leghtas** [comment]
I am in favour of changing names. I am also terrible with names, but I think its good to have something easy to pronounce, maybe `exopy `instead ?

**Comment by bhuard** [comment]
It would be great if the word actually exists. Running in an acronym generator leads to catchier names that are free in PyPI such as:
RASCassE | veRsatile Acquisition Software Complex Experiment
VAChERIN | Versatile softwAre Complex ExpeRImeNt
EpISCOPE | vErsatIle Software COmPlex Experiment
ASCENT | Acquisition Software Complex ExperimeNT

I like rascasse!

**Comment by MatthieuDartiailh** [comment]
If we were to go for a meaningful acronym, I would prefer one meaningful in english.

**Comment by MatthieuDartiailh** [comment]
Note the exopy can be considered an acronym for EXperiment Operation in Python, which is close to the previous meaning.

**Comment by MatthieuDartiailh** [comment]
Save if several people complain quickly, I will go with the name exopy (with the meaning of the above message). You have till tomorrow to voice your complaints with this name.

**Comment by lcontami** [comment]
I'm not a big fan of exopy but it is pronouncable, and a meaningful acronym. 
And I'm having a hard time finding something else.

**Comment by MatthieuDartiailh** [comment]
We are then set on exopy. Sorry @bhuard. I will proceed with the updates over the week so expect the install to be at least temporary off during the week.
