### ISSUE TITLE
LoopTask.LinspaceInterface : Allow the user to give a step that is not a divider of the span

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy#22]
For now, the span is divided into a linspace of n points, n being int(span/step), thus the actual step is not the one requested. This prevent the measure from running when the actual step has more digits than the instruments resolution !

Proposed fix: replace the linspace by an arange;
when the step isn't a divider of the span, then the "stop" point won't be the one requested; this could raise a warning.

**Comment by lcontami** [comment]
It's not a good idea to use arange; linspace handles floating numbers better.
The other possibility is to check in the end if the linspace step matches the requested step.
If not, raise a warning and redefine the linspace with a redefined stop = start + (num - 1) * step
(num being the number of points)

**Comment by MatthieuDartiailh** [comment]
Recently I have seen some weird values coming out of linspace so it may worth rounding the value manually to avoid weird issues with instruments.
This may be something you could look at @tcubaynes.

**Comment by MatthieuDartiailh** [comment]
Any progress @tcubaynes ?

**Comment by MatthieuDartiailh** [comment]
Will be closed by #76

**Comment by MatthieuDartiailh** [comment]
Closed by #78
