### ISSUE TITLE
compare notes

### ISSUE THREAD

**Issue by tacaswell** [Ecpy/ecpy#30]
At Brookhaven National Lab we have been build a similar in spirit, but very different in implementation, system (https://github.com/NSLS-II/bluesky) for driving data collection at NSLS-II.

We should touch base, can you drop me a line at tcaswell@bnl.gov

attn @danielballan @klauer

**Comment by MatthieuDartiailh** [comment]
As I answered by e-mail I am closing. Feel free to re-open if you prefer to discuss here rather than by private mail.
