### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by PhilipVinc** [Ecpy/ecpy#40]
In application.rst

> If any of your plugin need to retain user preferences from one application run to the next it should use the built-in preferences management system, which is straightforward. First your plugin should inherit from |HasPreferencesPlugin| and should call the parent class start method in its own

HasPreferencesPlugin should be HasPrefPlugin

**Comment by MatthieuDartiailh** [comment]
Will fix in my next PR. Thanks
