### ISSUE TITLE
Minor errors

### ISSUE THREAD

**Issue by PhilipVinc** [Ecpy/ecpy#41]
In ecpy/app/preferences/manifest.enaml lines 325-334

>         ActionItem:
            path = '/prefs/save_default'
            label = 'Save default'
            group = 'pref'
            command = 'hqc_meas.preferences.save'
        ActionItem:
            path = '/prefs/load_default'
            label = 'Load default'
            group = 'pref'
            command = 'hqc_meas.preferences.load'

hqc_meas is of course a leftover from the porting.

**Comment by PhilipVinc** [comment]
In ecpy/instruments/manifest.enaml line 472

>                 return BasicErrorDisplay(kind='Driver information validation',

BasicErrorDisplay should be BasicErrorsDisplay

**Comment by MatthieuDartiailh** [comment]
Thanks ! Will fix in next PR.

**Comment by PhilipVinc** [comment]
Ecpy/tasks/declarations.py 


line 169
"t_cls" should be "t_view" otherwise the error is a bit cryptic. 
line 583
"c_cls" should be "view" for the same reason

**Comment by MatthieuDartiailh** [comment]
Fixed for next PR.
