### ISSUE TITLE
Load sequence bug

### ISSUE THREAD

**Issue by leghtas** [Ecpy/ecpy#84]
When working on a measure which transfers a pulse sequence to the AWG, if we then switch to the pulse workspace editor to modify the pulse sequence, then go back to the measure to refresh the pulse, or load it again, the system crashes.

**Comment by MatthieuDartiailh** [comment]
Can you post the log ?

**Comment by leghtas** [comment]
[ecpy2017-01-27_8.txt](https://github.com/Ecpy/ecpy/files/735568/ecpy2017-01-27_8.txt)

**Comment by MatthieuDartiailh** [comment]
I tried to reproduce locally and failed could you describe exactly what you did to end up with that bug ?

**Comment by MatthieuDartiailh** [comment]
Closing as I believe we solved this.
