### ISSUE TITLE
Speed up demodulation in demod task

### ISSUE THREAD

**Issue by leghtas** [Ecpy/ecpy#86]
When data is acquired from an acquisition card, we extract I and Q by multiplying the raw traces by sin and cos, and then taking the mean. This operation, can, in some cases, be the limiting factor for how fast we can take data. Maybe there are tricks we can play in the demodulation task to make it faster?

**Comment by MatthieuDartiailh** [comment]
Moved to https://github.com/Ecpy/ecpy_hqc_legacy/issues/11
